# name: API Tests

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "backend/**"

# jobs:
#   test-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         run: |
#           cd backend
#           npm install

#       - name: Run API tests
#         run: |
#           cd backend
#           npm test
